name: "release"

env:
  SUBWASM_VERSION: 0.18.0

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or commit to build from"
        required: true
        default: "main"
      release_name:
        description: "Name of the new release (e.g. Polkadot stable2412)"
        required: true
      release_tag:
        description: "Tag of the new release (e.g. polkadot-stable2412)"
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          release_name: "${{ github.event.inputs.release_name }}"
          target_commitish: ${{ github.event.inputs.ref }}
          generate_release_notes: true